version: '3.8' 
services:
  remote-viewing:
    container_name: remote-viewing
    image: remoteviewing:latest
    ports:
      - "5000:5000" # Host to container port mapping.
    environment:
      - UNSPLASH_ACCESS_KEY=YOUR_UNSPLASH_ACCESS_KEY_HERE # Replace with your actual Unsplash access key.
      - TZ=America/New_York # Set the timezone for the Docker container.
      - SCHEDULE_UNIT=minutes # Unit of time for scheduling. Options: "seconds", "minutes", "hours", etc.
      - SCHEDULE_VALUE=5 # The value for the scheduling. Can be replaced with any integer.
      - FLASK_SECRET_KEY=YOUR_FLASK_SECRET_KEY_HERE # Replace with your actual Flask secret key.
      - DATABASE_URI=sqlite:////data/remote_viewing.db # URI for the database. Change if your database is located elsewhere.
      - SESSION_LIFETIME_DAYS=7 # Number of days before a session expires.
    volumes:
      - /srv/docker/remoteviewing:/data # Standard Linux path for Docker volumes.
    restart: unless-stopped # Container restart policy.

# Ensure the host directory exists with correct permissions before starting:
# sudo mkdir -p /srv/docker/remoteviewing
# sudo chmod -R 755 /srv/docker/remoteviewing
