version: '3.8' 
services:
  remote-viewing:
    container_name: remote-viewing # This is the name of the Docker container. You can change it to whatever you want.
    image: remoteviewing:latest # This is the Docker image that will be used to create the container. You can replace it with any other Docker image.
    ports:
      - "5000:5000" # This maps the port 6002 inside the Docker container to the port 6002 on the host machine. You can change the host port (the first one) to any available port on your host machine.
    environment:
      - UNSPLASH_ACCESS_KEY=-YOUR_UNSPLASH_ACCESS_KEY_HERE # This is an environment variable for the Unsplash access key. Replace the placeholder with your actual Unsplash access key.
      - TZ=America/New_York # This sets the timezone of the Docker container. Replace it with your preferred timezone.
      - SCHEDULE_UNIT=minutes # This is the unit of time for scheduling. You can replace "minutes" with "seconds", "hours", etc.
      - SCHEDULE_VALUE=5 # This is the value for the scheduling. You can replace "5" with any integer.
      - FLASK_SECRET_KEY=YOUR_UNSPLASH_ACCESS_KEY_HERE # This is the secret key for Flask. Replace the placeholder with your actual Flask secret key.
      - DATABASE_URI=sqlite:////data/remote_viewing.db # This is the URI for the database. Replace "/data/remote_viewing.db" with the path to your database file inside the Docker container.
    volumes:
      - /volume1/docker/remoteviewing:/data # This mounts the "/volume1/docker/remoteviewing" directory on the host machine to the "/data" directory inside the Docker container. You can replace "/volume1/docker/remoteviewing" with any directory on your host machine, and "/data" with any directory inside the Docker container.
